### ISSUE TITLE
Published npm version is not reflected in repository and code

### ISSUE THREAD

**Issue by adzialocha** [CirclesUBI/safe-contracts#4]
The .git tags, npm package and codebase seem to be out-of-sync:

**Gnosis Safe Code**
* Safe Contracts version in `master` is `1.2.0`: https://github.com/CirclesUBI/safe-contracts/blob/master/contracts/GnosisSafe.sol#L21
* in published npm package its `1.1.1`

**@circles/safe-contracts package**

* Published npm version of https://www.npmjs.com/package/@circles/safe-contracts is `1.0.17`
* Tags exist are up to `1.0.0` (I guess from the forked original repo): https://github.com/CirclesUBI/safe-contracts/tags
* [`package.json`](https://github.com/CirclesUBI/safe-contracts/blob/master/package.json#L3) says `1.0.11`

Do you have a local version of this repo with the right code and tags @ana0?

**Comment by JacqueGM** [comment]
@ana0   can you check @adzialocha  comments above? I would like to start the process of updating the contracts but there is that inconsistency between what is published in npm and the tags. 

Thanks!

**Comment by JacqueGM** [comment]
answers from @ana0 : 
there's no code there that you don't also have - you should build off of the npm version, which I believe is the one we also deployed, with highest package.json number

It's verified here: https://blockscout.com/xdai/mainnet/address/0x2CB0ebc503dE87CFD8f0eCEED8197bF7850184ae/read-contract#address-tabs

During dev, we updated the safe to 1.2.0 but had to downgrade before launch because the safe team hadn't updated the relayer. If I recall all changes between our master 1.0.11 and 1.0.17 were the downgrade, and me running into problems with npm org permissions

As Andreas said in the issue, the tags in that repo are from the original gnosis one - my commits there are from before our team was using tags. Fix here I think is just to add a tags for your current top versions

All the best,
- Sarah

**Comment by llunaCreixent** [comment]
The issue with the `v1.0.17` is that in the `build/contracts/GnosisSafe.json`, the setup method is defined with 7 parameters (the `fallbackHandler` is missing), so that's the reason why we use sometimes the `v1.0.14`.

**Comment by llunaCreixent** [comment]
new version `[1.0.18](https://www.npmjs.com/package/@circles/safe-contracts/v/1.0.18)` released to solve the issue. Now in testing phase

**Comment by llunaCreixent** [comment]
Use `@circles/safe-contracts@1.0.14`, since it is the correct one.
